version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:ap-south-1:241344156234:cluster/tomact"
        LoadBalancerInfo:
          ContainerName: "SampleApplicationName"
          ContainerPort: 80
        # Optional properties
        PlatformVersion: "LATEST"
        NetworkConfiguration:
          AwsvpcConfiguration:
            Subnets: ["subnet-04f90dfc21602d827", "subnet-0762ccd215d23800b"]
            SecurityGroups: [" sg-0e36bb45f3e541c93"]
            AssignPublicIp: "ENABLED"
        CapacityProviderStrategy:
          - Base: 0
            CapacityProvider: "FARGATE"
            Weight: 1
